#!/usr/bin/env python

from core import *

from tinyhelper import tokenize

import sys


DICTIONARY = {'exit'      : sys.exit,
              # Arithmetic operators
              '+'         : add,
              '-'         : subtract,
              '*'         : multiply,
              '/'         : divide,
              'mod'       : mod,
              # Stack operations
              'drop'      : drop,
              'swap'      : swap,
              'dup'       : dup,
              '.'         : dot,
              '.s'        : dot_s,
              # Let's get meta!
              'words'     : words,
              ':'         : define_word}
